services:
  backend:
    build: ./backend
    env_file: ./backend/.env.production
    ports:
      - "7001:7001"
    restart: unless-stopped
    volumes:
      - ./data/yjs-db:/app/yjs-db

  frontend:
    build: ./frontend
    ports:
      - "7000:80"
    restart: unless-stopped
