services:
  frontend:
    build: ./frontend
    ports:
      - "7000:80"
    restart: unless-stopped

  yjs-server:
    build: ./y-redis
    ports:
      - "7002:3002"
    command: node ./bin/server.js --no-colors
    env_file: ./y-redis/.env
    depends_on:
      - minio
      - redis
  yjs-worker:
    build: ./y-redis
    command: node ./bin/worker.js --no-colors
    env_file: ./y-redis/.env
    depends_on:
      - minio
      - redis
  redis:
    image: redis:alpine
  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address :9001
    volumes:
      - ./data/doc-storage:/data

networks:
  app_network:
    driver: bridge
